### ISSUE TITLE
Refactoring Population->Number to Population->Size

### ISSUE THREAD

**Issue by tclose** [INCF/nineml#75]
This is a little pedantic, but in expanding the spec I found a case where I would like to use `Number` for a different purpose than specifying the "size" of a population and realised that `Population`>`Size` was probably a better name for that anyway.

Does anyone feel strongly about this? If not, I thought it would be a change that would be good to make version 1.0 but if it is too late/much of a hassle at this point then no worries.

**Comment by apdavison** [comment]
I would prefer "size", but I guess it depends if Ivan has already submitted the tech paper manuscript.

**Comment by tclose** [comment]
This change was agreed upon in the last meeting and has been added to the spec. PR #84 implements this for the python library.
